name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: write  # Required for creating releases

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper git describe
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get version info
      id: version
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Get commit hash
        COMMIT=$(git rev-parse --short HEAD)
        echo "commit=$COMMIT" >> $GITHUB_OUTPUT
        
        # Get build date
        BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
        
        echo "Building version: $VERSION"
    
    - name: Run tests
      run: |
        go mod tidy
        go test ./... -v
    
    - name: Build binary
      run: |
        go mod tidy
        go build -ldflags "\
          -X 'github.com/amoga-io/run/cmd.Version=${{ steps.version.outputs.version }}' \
          -X 'github.com/amoga-io/run/cmd.GitCommit=${{ steps.version.outputs.commit }}' \
          -X 'github.com/amoga-io/run/cmd.BuildDate=${{ steps.version.outputs.build_date }}'" \
          -o run .
    
    - name: Test built binary
      run: |
        ./run version
        ./run --help
    
    - name: Get release notes from tag annotation
      id: release_notes
      run: |
        # Get the tag annotation message
        TAG_MESSAGE=$(git tag -l --format='%(contents)' ${{ steps.version.outputs.version }})
        
        # Set as output with proper delimiter
        echo "release_notes<<DELIMITER" >> $GITHUB_OUTPUT
        echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
        echo "DELIMITER" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          ${{ steps.release_notes.outputs.release_notes }}
          
          ---
          
          ## Installation
          
          ```bash
          curl -fsSL https://raw.githubusercontent.com/amoga-io/run/main/scripts/install.sh | bash
          ```
          
          ## Build Information
          - **Version**: ${{ steps.version.outputs.version }}
          - **Git Commit**: ${{ steps.version.outputs.commit }}
          - **Build Date**: ${{ steps.version.outputs.build_date }}
          - **Go Version**: 1.21
          
        draft: false
        prerelease: false
