name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Set up test environment
      run: |
        mkdir -p $HOME/.run
        cp -r scripts $HOME/.run/
        echo "Test environment created"
    
    - name: Run tests
      run: |
        go test -v ./...
      env:
        TESTING: "true"
        HOME: ${{ github.workspace }}
    
    - name: Run tests with coverage
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html
      env:
        TESTING: "true"
        HOME: ${{ github.workspace }}
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out 